version: '3.4' 
services:
   ea1:
     container_name: ea-1
     restart: unless-stopped
     image: public.ecr.aws/chainlink/adapters/coingecko-adapter:latest
     env_file: coingecko.env
     ports:
       - 8080:8080
     networks:
       - chainlink
   ea2: 
     container_name: ea-2 
     restart: unless-stopped 
     image: public.ecr.aws/chainlink/adapters/coinpaprika-adapter:latest 
     env_file: coinpaprika.env 
     ports: 
       - 8081:8080 
     networks: 
       - chainlink
   ea3:  
     container_name: ea-3 
     restart: unless-stopped  
     image: public.ecr.aws/chainlink/adapters/coinmarketcap-adapter:latest  
     env_file: coinmarketcap.env  
     ports: 
       - 8082:8080  
     networks:  
       - chainlink
networks: 
  chainlink:
    name: chainlink
    driver: bridge
