global: 
 scrape_interval: 5s 
 external_labels: 
   monitor: 'my-monitor'
   origin_prometheus: prometheus01
rule_files: 
 - 'alert.rules' 
scrape_configs: 
 - job_name: 'prometheus' 
   basic_auth: 
      username: <user-name>  # add here your Username of the prometheus authentication login 
      password: <password>  # add here your Password of the prometheus authentication login 
   static_configs: 
     - targets: ['localhost:9090'] 
   scheme: https 
   tls_config: 
     ca_file: /.tls/prometheus.crt 
 - job_name: 'node-exporter' 
   basic_auth: 
      username: <user-name>  # add here your Username of the node-exporter authentication login -- i try to keep this the same as prometheus 
      password: <password>  # add here your pw of the node-exporter authentication login 
   static_configs: 
     - targets: ['CONTAINER-ID:9100']  # add the container ID of your running node-exporter 
   scheme: https 
   tls_config:
#    ca_file: /tls/prometheus.crt 
#    cert_file: /tls/prometheus.crt 
#    key_file: /tls/prometheus.key 
     insecure_skip_verify: true 
 - job_name: 'chainlink_p1' 
   static_configs: 
     - targets: ['CONTAINER-ID:6689']  # add the container ID of your running Node and if you use a diffrent port you can also configure it 
   scheme: https 
   tls_config: 
     insecure_skip_verify: true 
 - job_name: 'externalAdapter_1' 
   static_configs: 
     - targets: ['CONTAINERID:9080']  # add the container ID of your running external adapter and if you use a diffrent port you can also configure it 
   scheme: http 
   tls_config: 
     insecure_skip_verify: true 
 - job_name: 'externalAdapter_2' 
   static_configs: 
     - targets: ['CONTAINERID:9080']  # add the container ID of your running external adapter and if you use a diffrent port you can also configure it 
   scheme: http 
   tls_config: 
     insecure_skip_verify: true 
remote_write: 
 - url: PROMETHEUS-REMOTE-WRITE-URL-FROM-GRAFANA-CLOUD
   basic_auth: 
      username: USER-NAME-FROM-GRAFANA-CLOUD 
      password: PW-FROM-GRAFANA-CLOUD
